module.exports.categories = [
  "Smileys & Emotion",
  "People & Body",
  "Animals & Nature",
  "Food & Drink",
  "Travel & Places",
  "Activities",
  "Objects",
  "Symbols",
  "Flags",
]

module.exports.subcategories = [
  "face-smiling",
  "face-affection",
  "face-tongue",
  "face-hand",
  "face-neutral-skeptical",
  "face-sleepy",
  "face-unwell",
  "face-hat",
  "face-glasses",
  "face-concerned",
  "face-negative",
  "face-costume",
  "cat-face",
  "monkey-face",
  "emotion",
  "hand-fingers-open",
  "hand-fingers-partial",
  "hand-single-finger",
  "hand-fingers-closed",
  "hands",
  "hand-prop",
  "body-parts",
  "person",
  "person-gesture",
  "person-role",
  "person-fantasy",
  "person-activity",
  "person-sport",
  "person-resting",
  "family",
  "person-symbol",
  "animal-mammal",
  "animal-bird",
  "animal-amphibian",
  "animal-reptile",
  "animal-marine",
  "animal-bug",
  "plant-flower",
  "plant-other",
  "food-fruit",
  "food-vegetable",
  "food-prepared",
  "food-asian",
  "food-marine",
  "food-sweet",
  "drink",
  "dishware",
  "place-map",
  "place-geographic",
  "place-building",
  "place-religious",
  "place-other",
  "transport-ground",
  "transport-water",
  "transport-air",
  "hotel",
  "time",
  "sky & weather",
  "event",
  "award-medal",
  "sport",
  "game",
  "arts & crafts",
  "clothing",
  "sound",
  "music",
  "musical-instrument",
  "phone",
  "computer",
  "light & video",
  "book-paper",
  "money",
  "mail",
  "writing",
  "office",
  "lock",
  "tool",
  "science",
  "medical",
  "household",
  "other-object",
  "transport-sign",
  "warning",
  "arrow",
  "religion",
  "zodiac",
  "av-symbol",
  "gender",
  "math",
  "punctuation",
  "currency",
  "other-symbol",
  "keycap",
  "alphanum",
  "geometric",
  "flag",
  "country-flag",
  "subdivision-flag",
]

module.exports.categoryToSubs = {
  "Smileys & Emotion": [
    "face-smiling",
    "face-affection",
    "face-tongue",
    "face-hand",
    "face-neutral-skeptical",
    "face-sleepy",
    "face-unwell",
    "face-hat",
    "face-glasses",
    "face-concerned",
    "face-negative",
    "face-costume",
    "cat-face",
    "monkey-face",
    "emotion",
  ],
  "People & Body": [
    "hand-fingers-open",
    "hand-fingers-partial",
    "hand-single-finger",
    "hand-fingers-closed",
    "hands",
    "hand-prop",
    "body-parts",
    "person",
    "person-gesture",
    "person-role",
    "person-fantasy",
    "person-activity",
    "person-sport",
    "person-resting",
    "family",
    "person-symbol",
  ],
  "Animals & Nature": [
    "animal-mammal",
    "animal-bird",
    "animal-amphibian",
    "animal-reptile",
    "animal-marine",
    "animal-bug",
    "plant-flower",
    "plant-other",
  ],
  "Food & Drink": [
    "food-fruit",
    "food-vegetable",
    "food-prepared",
    "food-asian",
    "food-marine",
    "food-sweet",
    "drink",
    "dishware",
  ],
  "Travel & Places": [
    "place-map",
    "place-geographic",
    "place-building",
    "place-religious",
    "place-other",
    "transport-ground",
    "transport-water",
    "transport-air",
    "hotel",
    "time",
    "sky & weather",
  ],
  Activities: ["event", "award-medal", "sport", "game", "arts & crafts"],
  Objects: [
    "clothing",
    "sound",
    "music",
    "musical-instrument",
    "phone",
    "computer",
    "light & video",
    "book-paper",
    "money",
    "mail",
    "writing",
    "office",
    "lock",
    "tool",
    "science",
    "medical",
    "household",
    "other-object",
  ],
  Symbols: [
    "transport-sign",
    "warning",
    "arrow",
    "religion",
    "zodiac",
    "av-symbol",
    "gender",
    "math",
    "punctuation",
    "currency",
    "other-symbol",
    "keycap",
    "alphanum",
    "geometric",
  ],
  Flags: ["flag", "country-flag", "subdivision-flag"],
}

module.exports.subToCategory = {
  "face-smiling": "Smileys & Emotion",
  "face-affection": "Smileys & Emotion",
  "face-tongue": "Smileys & Emotion",
  "face-hand": "Smileys & Emotion",
  "face-neutral-skeptical": "Smileys & Emotion",
  "face-sleepy": "Smileys & Emotion",
  "face-unwell": "Smileys & Emotion",
  "face-hat": "Smileys & Emotion",
  "face-glasses": "Smileys & Emotion",
  "face-concerned": "Smileys & Emotion",
  "face-negative": "Smileys & Emotion",
  "face-costume": "Smileys & Emotion",
  "cat-face": "Smileys & Emotion",
  "monkey-face": "Smileys & Emotion",
  emotion: "Smileys & Emotion",
  "hand-fingers-open": "People & Body",
  "hand-fingers-partial": "People & Body",
  "hand-single-finger": "People & Body",
  "hand-fingers-closed": "People & Body",
  hands: "People & Body",
  "hand-prop": "People & Body",
  "body-parts": "People & Body",
  person: "People & Body",
  "person-gesture": "People & Body",
  "person-role": "People & Body",
  "person-fantasy": "People & Body",
  "person-activity": "People & Body",
  "person-sport": "People & Body",
  "person-resting": "People & Body",
  family: "People & Body",
  "person-symbol": "People & Body",
  "animal-mammal": "Animals & Nature",
  "animal-bird": "Animals & Nature",
  "animal-amphibian": "Animals & Nature",
  "animal-reptile": "Animals & Nature",
  "animal-marine": "Animals & Nature",
  "animal-bug": "Animals & Nature",
  "plant-flower": "Animals & Nature",
  "plant-other": "Animals & Nature",
  "food-fruit": "Food & Drink",
  "food-vegetable": "Food & Drink",
  "food-prepared": "Food & Drink",
  "food-asian": "Food & Drink",
  "food-marine": "Food & Drink",
  "food-sweet": "Food & Drink",
  drink: "Food & Drink",
  dishware: "Food & Drink",
  "place-map": "Travel & Places",
  "place-geographic": "Travel & Places",
  "place-building": "Travel & Places",
  "place-religious": "Travel & Places",
  "place-other": "Travel & Places",
  "transport-ground": "Travel & Places",
  "transport-water": "Travel & Places",
  "transport-air": "Travel & Places",
  hotel: "Travel & Places",
  time: "Travel & Places",
  "sky & weather": "Travel & Places",
  event: "Activities",
  "award-medal": "Activities",
  sport: "Activities",
  game: "Activities",
  "arts & crafts": "Activities",
  clothing: "Objects",
  sound: "Objects",
  music: "Objects",
  "musical-instrument": "Objects",
  phone: "Objects",
  computer: "Objects",
  "light & video": "Objects",
  "book-paper": "Objects",
  money: "Objects",
  mail: "Objects",
  writing: "Objects",
  office: "Objects",
  lock: "Objects",
  tool: "Objects",
  science: "Objects",
  medical: "Objects",
  household: "Objects",
  "other-object": "Objects",
  "transport-sign": "Symbols",
  warning: "Symbols",
  arrow: "Symbols",
  religion: "Symbols",
  zodiac: "Symbols",
  "av-symbol": "Symbols",
  gender: "Symbols",
  math: "Symbols",
  punctuation: "Symbols",
  currency: "Symbols",
  "other-symbol": "Symbols",
  keycap: "Symbols",
  alphanum: "Symbols",
  geometric: "Symbols",
  flag: "Flags",
  "country-flag": "Flags",
  "subdivision-flag": "Flags",
}
